* NAME: RISHABH PATIL
* SAP: 60009200056
* BATCH: K2

# 1. Synthetic Data from Sklearn and Scratch

## From Sklearn

In [ ]:
import numpy as np
import pandas as pd
import math

### Create Synthetic Data

In [ ]:
from sklearn.datasets import make_classification
X,y = make_classification(n_samples=500, n_features=4, n_classes=2, random_state=50)

In [ ]:
# X, y

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
# mean = np.mean(X_train[0])
# mean

### Standardization

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Fit and Predict

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)

### Metrics

In [ ]:
from sklearn.metrics import f1_score, confusion_matrix, accuracy_score
print(f"Accuracy: {accuracy_score(y_test, y_pred)}\n")
print(f"Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}\n")
print(f"F1 Score of Model : {f1_score(y_test, y_pred)}")

Accuracy: 0.976

Confusion Matrix: 
[[57  0]
 [ 3 65]]

F1 Score of Model : 0.9774436090225563


## From Scratch

In [ ]:
import numpy as np
from numpy import log,dot,exp,shape
import matplotlib.pyplot as plt

In [ ]:
from sklearn.datasets import make_classification
X,y = make_classification(n_samples=500, n_features=4, n_classes=2, random_state=50)

### Split Data

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

### Creating Logistic Regression Class

In [ ]:
class logistic_regression:
    def sigmoid(self,z):
        sig = 1/(1+exp(-z))
        return sig
    def initialize(self,X):
        weights = np.zeros((shape(X)[1]+1,1))
        X = np.c_[np.ones((shape(X)[0],1)),X]
        return weights,X
    def fit(self,X,y,alpha=0.001,iter=400):
        weights,X = self.initialize(X)
        def cost(theta):
            z = dot(X,theta)
            cost0 = y.T.dot(log(self.sigmoid(z)))
            cost1 = (1-y).T.dot(log(1-self.sigmoid(z)))
            cost = -((cost1 + cost0))/len(y)
            return cost
        cost_list = np.zeros(iter,)
        for i in range(iter):
            weights = weights - alpha*dot(X.T,self.sigmoid(dot(X,weights))-np.reshape(y,(len(y),1)))
            cost_list[i] = cost(weights)
        self.weights = weights
        return cost_list
    def predict(self,X):
        z = dot(self.initialize(X)[1],self.weights)
        lis = []
        for i in self.sigmoid(z):
            if i>0.5:
                lis.append(1)
            else:
                lis.append(0)
        return lis

### F1 Score Func

In [ ]:
def f1Score(y,y_hat):
    tp,tn,fp,fn = 0,0,0,0
    for i in range(len(y)):
        if y[i] == 1 and y_hat[i] == 1:
            tp += 1
        elif y[i] == 1 and y_hat[i] == 0:
            fn += 1
        elif y[i] == 0 and y_hat[i] == 1:
            fp += 1
        elif y[i] == 0 and y_hat[i] == 0:
            tn += 1
    precision = tp/(tp+fp)
    recall = tp/(tp+fn)
    f1_score = 2*precision*recall/(precision+recall)
    return f1_score

### Standardization

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Predicting

In [ ]:
logistic = logistic_regression()
model= logistic.fit(X_train,y_train)
y_pred = logistic.predict(X_test)

### F1 Score

In [ ]:
f1Score(y_test, y_pred)

0.9774436090225563

# 2. Multinomial Iris.csv Dataset

### Data Pre Processing

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
iris = pd.read_csv('/content/Iris (2).csv')
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

### Label Encoding Species Column

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

iris['Species']= encoder.fit_transform(iris['Species'])
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

In [ ]:
y=iris.iloc[:,-1]
x=iris.drop(['Species'],axis=1)


### Splitting Data and Training Model

In [ ]:
# Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(multi_class="multinomial",random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


### Metrics

In [ ]:
from sklearn.metrics import f1_score, confusion_matrix, accuracy_score
print(f"Accuracy: {accuracy_score(y_test, y_pred)}\n")
print(f"Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}\n")
print(f"F1 Score of Model : {f1_score(y_test, y_pred, average='micro')}")

Accuracy: 1.0

Confusion Matrix: 
[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]

F1 Score of Model : 1.0


# 3. Airplane.csv Dataset with and without regularization

### Data Processing

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
train = pd.read_csv('train.csv')
train.head()
test = pd.read_csv('test.csv')

In [ ]:
train.isna().any()
test.isna().any()

Unnamed: 0                           False
id                                   False
Gender                               False
Customer Type                        False
Age                                  False
Type of Travel                       False
Class                                False
Flight Distance                      False
Inflight wifi service                False
Departure/Arrival time convenient    False
Ease of Online booking               False
Gate location                        False
Food and drink                       False
Online boarding                      False
Seat comfort                         False
Inflight entertainment               False
On-board service                     False
Leg room service                     False
Baggage handling                     False
Checkin service                      False
Inflight service                     False
Cleanliness                          False
Departure Delay in Minutes           False
Arrival Del

In [ ]:
train = train.drop(['id','Unnamed: 0', 'Arrival Delay in Minutes'], axis=1)
test = test.drop(['id','Unnamed: 0', 'Arrival Delay in Minutes'], axis=1)
train

Gender      Customer Type  Age   Type of Travel     Class  \
0         Male     Loyal Customer   13  Personal Travel  Eco Plus   
1         Male  disloyal Customer   25  Business travel  Business   
2       Female     Loyal Customer   26  Business travel  Business   
3       Female     Loyal Customer   25  Business travel  Business   
4         Male     Loyal Customer   61  Business travel  Business   
...        ...                ...  ...              ...       ...   
103899  Female  disloyal Customer   23  Business travel       Eco   
103900    Male     Loyal Customer   49  Business travel  Business   
103901    Male  disloyal Customer   30  Business travel  Business   
103902  Female  disloyal Customer   22  Business travel       Eco   
103903    Male     Loyal Customer   27  Business travel  Business   

        Flight Distance  Inflight wifi service  \
0                   460                      3   
1                   235                      3   
2                  1142                      2   
3                   562                      2   
4                   214                      3   
...                 ...                    ...   
103899              192                      2   
103900             2347                      4   
103901             1995                      1   
103902             1000                      1   
103903             1723                      1   

        Departure/Arrival time convenient  Ease of Online booking  \
0                                       4                       3   
1                                       2                       3   
2                                       2                       2   
3                                       5                       5   
4                                       3                       3   
...                                   ...                     ...   
103899                                  1                       2   
103900                                  4                       4   
103901                                  1                       1   
103902                                  1                       1   
103903                                  3                       3   

        Gate location  ...  Seat comfort  Inflight entertainment  \
0                   1  ...             5                       5   
1                   3  ...             1                       1   
2                   2  ...             5                       5   
3                   5  ...             2                       2   
4                   3  ...             5                       3   
...               ...  ...           ...                     ...   
103899              3  ...             2                       2   
103900              4  ...             5                       5   
103901              3  ...             5                       4   
103902              5  ...             1                       1   
103903              3  ...             1                       1   

        On-board service  Leg room service  Baggage handling  Checkin service  \
0                      4                 3                 4                4   
1                      1                 5                 3                1   
2                      4                 3                 4                4   
3                      2                 5                 3                1   
4                      3                 4                 4                3   
...                  ...               ...               ...              ...   
103899                 3                 1                 4                2   
103900                 5                 5                 5                5   
103901                 3                 2                 4                5   
103902                 4                 5                 1                5   
103903                 1                 

In [ ]:
train.columns

Index(['Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class',
       'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'satisfaction'],
      dtype='object')

### Label Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
columns = ['Gender', 'Customer Type', 'Type of Travel', 'Class','satisfaction']
for column in columns:
  train[column]= encoder.fit_transform(train[column])
  test[column]= encoder.fit_transform(test[column])

train.head()

Gender  Customer Type  Age  Type of Travel  Class  Flight Distance  \
0       1              0   13               1      2              460   
1       1              1   25               0      0              235   
2       0              0   26               0      0             1142   
3       0              0   25               0      0              562   
4       1              0   61               0      0              214   

   Inflight wifi service  Departure/Arrival time convenient  \
0                      3                                  4   
1                      3                                  2   
2                      2                                  2   
3                      2                                  5   
4                      3                                  3   

   Ease of Online booking  Gate location  ...  Seat comfort  \
0                       3              1  ...             5   
1                       3              3  ...             1   
2                       2              2  ...             5   
3                       5              5  ...             2   
4                       3              3  ...             5   

   Inflight entertainment  On-board service  Leg room service  \
0                       5                 4                 3   
1                       1                 1                 5   
2                       5                 4                 3   
3                       2                 2                 5   
4                       3                 3                 4   

   Baggage handling  Checkin service  Inflight service  Cleanliness  \
0                 4                4                 5            5   
1                 3                1                 4            1   
2                 4                4                 4            5   
3                 3                1                 4            2   
4                 4                3                 3            3   

   Departure Delay in Minutes  satisfaction  
0                          25             0  
1                           1             0  
2                           0             1  
3                          11             0  
4                           0             1  

[5 rows x 22 columns]

In [ ]:
y_train = train.iloc[:, -1]
y_test = test.iloc[:, -1]
X_train = train.iloc[:, :-1]
X_test = test.iloc[:, :-1]

### Feature Scaling

In [ ]:

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**L1 Regularisation is not created in Logistic Regression function in Scikit-learn, only *'l2' and 'none'* parameters for penalty are currently available**

### Without Regularisation

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(penalty='none',random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

from sklearn.metrics import f1_score, confusion_matrix, accuracy_score
print(f"Accuracy: {accuracy_score(y_test, y_pred)}\n")
print(f"Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}\n")
print(f"F1 Score of Model : {f1_score(y_test, y_pred)}")

Accuracy: 0.8711117955035418

Confusion Matrix: 
[[13126  1447]
 [ 1901  9502]]

F1 Score of Model : 0.8502147458840373


### With Regularisation L2

In [ ]:

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(penalty='l2', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

from sklearn.metrics import f1_score, confusion_matrix, accuracy_score
print(f"Accuracy: {accuracy_score(y_test, y_pred)}\n")
print(f"Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}\n")
print(f"F1 Score of Model : {f1_score(y_test, y_pred)}")

Accuracy: 0.8711117955035418

Confusion Matrix: 
[[13126  1447]
 [ 1901  9502]]

F1 Score of Model : 0.8502147458840373
